package me.nagaev.veles.common.ui.theme

import androidx.compose.ui.graphics.Color

// Palette derived from the launcher icon (deep emerald shield + gold bull/runes), issue #39.
// The gold "success" accent is mapped onto the tertiary role — M3 has no success role.

val md_theme_light_primary = Color(0xFF1E6B47)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFC9F2DC)
val md_theme_light_onPrimaryContainer = Color(0xFF00210F)
val md_theme_light_secondary = Color(0xFF6B5514)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFF6E3AE)
val md_theme_light_onSecondaryContainer = Color(0xFF221A00)
val md_theme_light_tertiary = Color(0xFF8A6D14)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFF7E4A8)
val md_theme_light_onTertiaryContainer = Color(0xFF241A00)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFBFAF3)
val md_theme_light_onBackground = Color(0xFF1A1C16)
val md_theme_light_surface = Color(0xFFFBFAF3)
val md_theme_light_onSurface = Color(0xFF1A1C16)
val md_theme_light_surfaceVariant = Color(0xFFDDE5DA)
val md_theme_light_onSurfaceVariant = Color(0xFF43483F)
val md_theme_light_outline = Color(0xFF73796C)
val md_theme_light_outlineVariant = Color(0xFFDDE5DA)
val md_theme_light_surfaceContainerLow = Color(0xFFF4F3EA)
val md_theme_light_surfaceContainer = Color(0xFFEEEDE1)
val md_theme_light_surfaceContainerHigh = Color(0xFFE8E7D9)
val md_theme_light_surfaceContainerHighest = Color(0xFFE2E1D1)
val md_theme_light_inverseSurface = Color(0xFF2F312A)
val md_theme_light_inverseOnSurface = Color(0xFFF1F1E7)
val md_theme_light_inversePrimary = Color(0xFF8FDBB0)
val md_theme_light_surfaceTint = md_theme_light_primary

val md_theme_dark_primary = Color(0xFF8FDBB0)
val md_theme_dark_onPrimary = Color(0xFF003920)
val md_theme_dark_primaryContainer = Color(0xFF00522F)
val md_theme_dark_onPrimaryContainer = Color(0xFFABF3C6)
val md_theme_dark_secondary = Color(0xFFE4C567)
val md_theme_dark_onSecondary = Color(0xFF3B2E00)
val md_theme_dark_secondaryContainer = Color(0xFF544000)
val md_theme_dark_onSecondaryContainer = Color(0xFFFFE18C)
val md_theme_dark_tertiary = Color(0xFFD8B84A)
val md_theme_dark_onTertiary = Color(0xFF3B2E00)
val md_theme_dark_tertiaryContainer = Color(0xFF544000)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFE18C)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF12140F)
val md_theme_dark_onBackground = Color(0xFFE3E3D9)
val md_theme_dark_surface = Color(0xFF12140F)
val md_theme_dark_onSurface = Color(0xFFE3E3D9)
val md_theme_dark_surfaceVariant = Color(0xFF414941)
val md_theme_dark_onSurfaceVariant = Color(0xFFC1C9BE)
val md_theme_dark_outline = Color(0xFF8B938A)
val md_theme_dark_outlineVariant = Color(0xFF414941)
val md_theme_dark_surfaceContainerLow = Color(0xFF1A1C16)
val md_theme_dark_surfaceContainer = Color(0xFF1E211A)
val md_theme_dark_surfaceContainerHigh = Color(0xFF282B23)
val md_theme_dark_surfaceContainerHighest = Color(0xFF33362D)
val md_theme_dark_inverseSurface = Color(0xFFE3E3D9)
val md_theme_dark_inverseOnSurface = Color(0xFF2F312A)
val md_theme_dark_inversePrimary = Color(0xFF1E6B47)
val md_theme_dark_surfaceTint = md_theme_dark_primary
